#!/bin/bash
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo -e "${GREEN}app${NC}"

cd ..
cd PrimeApps.App
export ASPNETCORE_ENVIRONMENT=Development
export AppSettings__ClientId=sample
export AppSettings__ClientSecret=secret
dotnet PrimeApps.App.dll --urls='http://localhost:5001'