#!/bin/bash
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -n "Password (press enter if empty)":
read -s password
export PGPASSWORD=$password

if [ "$( psql -U postgres -w -tAc "SELECT 1 FROM pg_database WHERE datname='postgres'" )" = '1' ]
then
    for arg in "$@"
    do
        if [ "$arg" == "--create" ] || [ "$arg" == "-c" ]
        then
            echo -e "${GREEN}Creating PrimeApps databases...${NC}"
            echo -e "${GREEN}Platform database${NC}"
            createdb -U postgres --template=template0 --encoding=UTF8 --lc-ctype=en-US --lc-collate=en-US platform
            psql -U postgres platform < platform.sql
            echo -e "${GREEN}Auth database${NC}"
            createdb -U postgres --template=template0 --encoding=UTF8 --lc-ctype=en-US --lc-collate=en-US auth
            psql -U postgres auth < auth.sql
            echo -e "${GREEN}app100 database${NC}"
            createdb -U postgres --template=template0 --encoding=UTF8 --lc-ctype=en-US --lc-collate=en-US app100
            rm app100.dmp
            echo -e "${GREEN}Downloading app100...${NC}"
            
            curl https://studio.primeapps.io/api/dump/download?appId=100 --output app100.dmp
            pg_restore -U postgres -Fc -d app100 app100.dmp
            psql -U postgres -d postgres -f app100_template.sql
            echo -e "${GREEN}All databases created successfully.${NC}"
        elif [ "$arg" == "--update" ] || [ "$arg" == "-u" ]
        then
            if [ -z "$2" ]
            then
                echo -e "${RED}App id cannot be null. Try like this: ./database -u 100${NC}"
            else
                echo -e "${GREEN}Removing app$2 database${NC}"
                psql -U postgres -d postgres -f "drop_app$2.sql"
                echo -e "${GREEN}Creating app$2 database${NC}"
                createdb -U postgres --template=template0 --encoding=UTF8 --lc-ctype=en-US --lc-collate=en-US "app$2"
                rm "app$2.dmp"
                echo -e "${GREEN}Downloading app$2...${NC}"
                curl "https://studio.primeapps.io/api/dump/download?appId=$2" --output "app$2.dmp"
                pg_restore -U postgres -Fc -d "app$2" "app$2.dmp"
                psql -U postgres -d postgres -f "app$2_template.sql"
                echo -e "${GREEN}app$2 updated successfully.${NC}"
            fi
        elif [ "$arg" == "--delete" ] || [ "$arg" == "-d" ]
        then
            echo -e "${GREEN}Removing PrimeApps databases...${NC}"
            psql -U postgres -d postgres -f drop.sql
            echo -e "${GREEN}All PrimeApps databases removed successfully.${NC}"
            echo -e "${GREEN}Removing tenant databases...${NC}"
            psql -U postgres -d postgres -f drop_tenant.sql
            echo -e "${GREEN}All tenant databases removed successfully.${NC}"
        elif [ "$arg" == "--delete-tenants" ] || [ "$arg" == "-dt" ]
        then
            echo -e "${GREEN}Removing tenant databases...${NC}"
            psql -U postgres -d postgres -f drop_tenant.sql
            echo -e "${GREEN}All tenant databases removed successfully.${NC}"
        fi
    done
else
    echo -e "${RED}Cannot connect database server.${NC}"
fi